name: Push to Dockerhub
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Get Dockerfile
        run: |
          git clone https://codeberg.org/grindhold/flohmarkt.git
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./flohmarkt
          push: true
          tags: yonggan/flohmarkt:daily
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
